# Generated by Django 5.2.11 on 2026-02-26 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0001_initial'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchscore',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.resume'),
        ),
        migrations.AlterUniqueTogether(
            name='matchscore',
            unique_together={('job', 'resume')},
        ),
    ]
