# Generated by Django 5.2.11 on 2026-03-05 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
        ('matching', '0002_initial'),
        ('resumes', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatchScore',
            new_name='Match',
        ),
    ]
