# Generated by Django 5.2.11 on 2026-03-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
