# Generated by Django 5.2.11 on 2026-03-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_cover_letter_application_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='applications/documents/'),
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='application',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='linkedin_profile',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
